### ISSUE TITLE
cmds not working

### ISSUE THREAD

**Issue by TheNightlamb** [OH221105/EconBot#2]
prefix is set everything is set up but the cmds arent working

**Comment by DEVUCP** [comment]
Aren't working how? is it throwing any errors or just doing nothing?
If its the latter, then maybe you didn't give the bot admin permissions so it can read channel messages.

**Comment by TheNightlamb** [comment]
no errors bots online its just doing nothing. bot needs admin perms? i did give it read msg perm but in the main.py do i have to only change the token right or do i have to give it more things?

**Comment by DEVUCP** [comment]
it could be a couple of things, after your issue was opened I realized a good couple of details missing in the setup & installation section of the README, that'll be updated very soon. for now though-

- Check that the token environment variable is set-up or that you've pasted the right token into the client run method call thats at the end of "main.py"

- Make sure you've ran the bot process once for it to generate the save file in the "saveload" directory. Then run again and wait for "LOGGED IN AS ####" to be printed on the terminal.

**Comment by TheNightlamb** [comment]
at the end it doesnt say logged in as it says logged in using static token and Shard ID None has connected to Gateway (im hosting the bot on a server). saveload file is been generated. now?

**Comment by DEVUCP** [comment]
it should look like this

![Screenshot 2024-09-19 095643](https://github.com/user-attachments/assets/07e084c4-3663-47fb-9709-7057902276f8)

**Comment by TheNightlamb** [comment]
![image](https://github.com/user-attachments/assets/764fe633-eef5-467c-8e39-4e29910dff79)

**Comment by DEVUCP** [comment]
Hm, and you said the save file has been generated? it should be named "userdata.pkl" in the saveload directory

**Comment by TheNightlamb** [comment]
in the saveload file there is two files saveload.py and __pycache__. uhh do i have to type in server ids or owner ids anywhere? cause i didnt do that

**Comment by DEVUCP** [comment]
Terminate the current process by pressing CRTL + C  in the terminal and run again.

**Comment by DEVUCP** [comment]
And no, you don't have to type in server ids or owner ids anywhere. Im about to commit and push the README changes, those should also help hopefully.

**Comment by TheNightlamb** [comment]
still no its just gives out this
![image](https://github.com/user-attachments/assets/4ccfa705-6b62-47dd-a517-f692dfd7e3b2)

**Comment by DEVUCP** [comment]
Thats odd. When setting up your bot did you tick on bot in the URL generator and administrator under bot permissions?

**Comment by TheNightlamb** [comment]
i did give it admin perms do i have to give it admin perms?

**Comment by DEVUCP** [comment]
I give it admin perms by default, it _could_ be the issue, I'm not 100% certain of course. If you don't feel comfortable giving it admin perms for your server you can try it on a burner server just to be sure its safe yourself.

Also, I've just pushed changes to the README, checkout the changes, they should help.

**Comment by TheNightlamb** [comment]
I have done all of it according to the readme page and i even added it to a burner server with admin perms and still not 
responding to cmds

**Comment by DEVUCP** [comment]
after you terminated the process, did it print out "saved!"? like so
![image](https://github.com/user-attachments/assets/796d7fa6-e149-4200-8918-951c976b7513)

**Comment by DEVUCP** [comment]
For the bot to function it must display the logged in message.

Basically, it looks for the save-file, if it doesn't find one to load, it doesn't function, but when its terminated it will generate one. So the next time you run it, there should be one, so it should just be able to find it and read it just fine.

You could try manually making a "userdata.pkl" file (keep it empty) and try to run the bot and see what happens.

**Comment by TheNightlamb** [comment]
nope you wanna take a look at my console rq? im at that point where im giving up pulled a over nighter tryna figure this out lol

**Comment by DEVUCP** [comment]
Yea of course, show me.

if you want faster communication my discord is devucp

**Comment by TheNightlamb** [comment]
fr sent if ya wanna delete this ticket and switch over to dc dat be much easier
